name: Metal Music
favicon: null
layout_spectrum: 0.8871232881210744
typography_spectrum: 0.49884868739172816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5567422376479954
  lightness: 0.3061747965402901
  saturation: 0.7558288702275604
  rhythmicContrast: 0.3460737850982696
purpose: []
